### ISSUE TITLE
ICA access token expiry not checked piror to use

### ISSUE THREAD

**Issue by scwatts** [umccr/gridss-purple-linx-nf#23]
* ICA access token lifetime has been shortened to 24 hours
* Expiry of an obtained access token is not checked before use
* It is now likely for GPL jobs to obtain a valid token at initialization that then becomes invalid during runtime

**Comment by alexiswl** [comment]
@reisingerf @andrewpatto @victorskl I think in light of this and other potentially unknown usecases, can we extended to 72 hour tokens?

**Comment by scwatts** [comment]
Thanks Alexis. For now this has been fixed in https://github.com/umccr/gridss-purple-linx-nf/commit/f61c405ddec25ccb52577aa87d3fb9cc8ad061ef. Presumably the expiry check is still required in the case that a GPL job is launched and obtains a token that will expire prior to workflow completion.

**Comment by reisingerf** [comment]
Happy to discuss or push up the lifetime if that unblocks issues, but I am not sure that's actually required.

The issue here, if I understand correctly, that the same token is used for multiple actions, which was not a problem for long running jobs. However, we could simply switch to a model where a new token is requested whenever needed (and specific for a request). That way the token is always "fresh" and does not have to have a long lifetime.

In the case of Stephen's fix, instead of checking if the current token is still valid long enough, could you just pull a new token that's guaranteed to last for 24h?

Are we aware of any situations where we need a token to last for more than 24h?

**Comment by scwatts** [comment]
Hi Florian, yes that's correct - an ICA access token is used for multiple interactions with GDS.

The token is obtained from `IcaSecretsPortal` in SM, and GPL is unable to create a fresh token itself since presumably access to the ICA API key is restricted. This means that GPL may obtain a token that has a very short time before expiry.

When the token was long lived this scenario was unlikely to occur but now that a token is valid for only 24 hours it is much more likely the token will expire during a GPL run.

So if a token obtained from `IcaSecretsPortal` is to expire during a run, GPL must be able to catch this at the point of interaction with GDS and obtain the newly rotated token (which is handled by `ica-credentials).

**Comment by scwatts** [comment]
Noting token lifetime and rotation details decided by @reisingerf @victorskl:

- 1 day rotation (1 day + X hours as determined by AWS; maximum rotation <48 hours)
- 48 hour token lifetime

Assuming time resolution used by the CRON job is in the order of minutes the shortest TTL possible is 1 minute, albeit unlikely. Checking token expiry is still necessary.

**Comment by victorskl** [comment]
Side note: 

I reckon, wanna roll [GPL-0.2.1](https://github.com/umccr/gridss-purple-linx-nf/milestone/1) as part of [Snowshoe](https://github.com/umccr/infrastructure/milestone/9)?

**Comment by scwatts** [comment]
Yeah! I need to resolve some issues with Conda package dependencies for the new Docker image but should otherwise be ready shortly
